Add files via upload
TudoDigital/Dynamics pull request #19
Opened 2022-03-28 09:16 UTC by rafaeldobies

inserido Arquivos do DER - BrModelo

@rtrevizoli

2022-03-29 22:39 UTC, Breno-Moura requested changes
Revisar mudanças de acordo com o feedback da Professora Juliana

2022-03-31 00:48 UTC, Breno-Moura approved these changes
Aprovada a revisão dos DER's

2022-04-01 22:21 UTC, michelrubens reviewed
Conferido.

2022-04-01 22:22 UTC, michelrubens approved these changes
Conferido.

2022-04-01 23:28 UTC, merged